---
include:
  - template: Jobs/Code-Intelligence.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Secure-Binaries.gitlab-ci.yml
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

set_variables:
  stage: .pre
  script:
    - ELIXIR_VERSION="$(awk -vFS='[ -]' '/^elixir/ { print $2 }' .tool-versions)"
    - ELIXIR_IMAGE="${CI_REGISTRY_IMAGE}/elixir:${ELIXIR_VERSION}-alpine-bash"
    - echo "ELIXIR_VERSION=${ELIXIR_VERSION}" >> variables.env
    - echo "ELIXIR_IMAGE=${ELIXIR_IMAGE}" >> variables.env
    - |
      # from https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - echo "CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY}" >> variables.env
    - echo "CI_APPLICATION_TAG=${CI_APPLICATION_TAG}" >> variables.env
    - echo "DOCKER_IMAGE=${CI_APPLICATION_REPOSITORY}:${CI_APPLICATION_TAG}" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

container_image:
  stage: build
  needs:
    - job: set_variables
      artifacts: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --build-arg ELIXIR_VERSION="${ELIXIR_VERSION}"
      --cache=true
      --context="${CI_PROJECT_DIR}"
      --dockerfile="${CI_PROJECT_DIR}/Dockerfile"
      --destination="${ELIXIR_IMAGE}"
      --destination="${DOCKER_IMAGE}"
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - .gitlab-ci.yml
        - .tool-versions
        - Dockerfile
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  stage: test
  needs:
    - job: set_variables
      artifacts: true
    - job: container_image
      optional: true
  image: ${ELIXIR_IMAGE}
  cache:
    key:
      files:
        - .tool-versions
        - mix.lock
    paths:
      - .cache
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: .cache/_build/test/lib/excercism_elixir/test-junit-report.xml
  coverage: '/^ *Line total: +(\d+\.\d+%) *$/'
  interruptible: true
  variables:
    MIX_ENV: test
  script:
    - apk add bash git
    - source .gitlab/ci.sh
    - ci_section lint-test-helpers ci_check_test_helpers
    - ci_section setup-hex mix local.hex --force --if-missing
    - ci_section setup-rebar mix local.rebar --force --if-missing
    - ci_section setup-deps mix do deps.get, deps.compile
    - ci_section audit-dependencies mix do hex.audit, deps.audit, deps.unlock --check-unused
    - ci_section test mix test --cover
    - ci_section test-junit-for-gitlab .gitlab/junit-for-gitlab
    - ci_section lint-format mix format --check-formatted
    - ci_section lint-credo-high mix credo suggest --format=oneline --min-priority=high
    - ci_section lint-credo-info mix credo suggest --format=oneline --mute-exit-status
